import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output=process.env.QA_OUTPUT||path.join(root,'work','qa');
fs.mkdirSync(output,{recursive:true});
const base=process.env.BASE_URL||'file://'+root+'/dist/index.html';
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
const page=await context.newPage();page.setDefaultTimeout(15000);const errors=[];const failures=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push([r.status(),r.url()]);});
await page.goto(base);await page.waitForFunction(()=>document.querySelector('#stay-result').textContent.length>20);
await page.screenshot({path:output+'/suwa-desktop.png',fullPage:true});
assert.equal(await page.locator('.calendar-day.selected').count(),5);
assert.match(await page.locator('#stay-result').textContent(),/兩種出現日期記載都在抵達前/);
await page.locator('#hero-art').evaluate(i=>i.decode());
assert.equal(await page.locator('#hero-art').evaluate(i=>i.complete&&i.naturalWidth>0),true);
await page.locator('#event-preview [data-event]').first().click();assert.equal(await page.locator('#event-dialog').evaluate(d=>d.open),true);
assert.match(await page.locator('#dialog-content').textContent(),/2018-02-02/);await page.keyboard.press('Escape');
await page.selectOption('#day','29');assert.equal(await page.locator('#date-error').isVisible(),true);
await page.selectOption('#year-select','2020');assert.equal(await page.locator('#date-error').isVisible(),false);
await page.selectOption('#year-select','2018');await page.selectOption('#month','12');await page.selectOption('#day','30');
assert.match(await page.locator('#stay-range').textContent(),/2017-12-30 → 2018-01-03/);
await page.locator('#arrival-slider').fill('0');assert.equal(await page.locator('#prev-day').isDisabled(),true);
await page.selectOption('#month','2');await page.selectOption('#day','3');
await page.locator('#calendar').scrollIntoViewIfNeeded();
const b=await page.locator('.calendar-day.start').boundingBox();const cellWidth=b.width;
await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+cellWidth*2,b.y+b.height/2,{steps:6});await page.mouse.up();
assert.equal(await page.locator('#day').inputValue(),'5');
await page.locator('.calendar-day').first().click();assert.equal(await page.locator('#day').inputValue(),'3');
await page.locator('.calendar-day').first().focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('calendar-day')),true);
await page.selectOption('#day','3');
await page.locator('#random-year').click();const randomYear=Number(await page.locator('#year-title').textContent());
assert.equal(await page.evaluate(y=>['occurred','not_observed'].includes(window.SUWA_DATA.winters.find(w=>w.winter_year===y).omiwatari_status),randomYear),true);
await page.selectOption('#year-select','1960');assert.match(await page.locator('#winter-status').textContent(),/尚無可核實/);
await page.selectOption('#year-select','2026');await page.locator('#year-notes summary').click();assert.match(await page.locator('#notes-content').textContent(),/有全面結冰紀錄/);
await page.locator('#archive-link').click();assert.equal(await page.locator('.year-cell').count(),150);
assert.equal(await page.locator('.year-cell.has-date-dispute').count(),2);
assert.equal(await page.locator('.year-cell.occurred.has-date-dispute[data-year="2004"]').count(),1);
assert.equal(await page.locator('#annual-dispute-legend').isHidden(),true);
assert.equal(await page.locator('#date-chart .year-date-mark').count(),150);
assert.equal(await page.locator('#rolling-chart .coverage-mark').count(),150);
await page.locator('.reading-vignette').scrollIntoViewIfNeeded();
await page.locator('.reading-vignette img').evaluate(i=>i.decode());
await page.selectOption('#stats-period','recent');assert.match(await page.locator('#stats-summary').textContent(),/全部 30 個冬季/);
assert.equal(await page.locator('#date-chart .year-date-mark').count(),30);
await page.selectOption('#stats-period','all');
await page.locator('.research-details summary').click();const dlPromise=page.waitForEvent('download');await page.locator('#export-csv').click();const dl=await dlPromise;await dl.saveAs(output+'/suwa-export.csv');assert.equal(fs.readFileSync(output+'/suwa-export.csv','utf8').trim().split('\n').length,151);
await page.locator('#stories-link').click();await page.getByRole('tab',{name:'湖的南北'}).click();assert.match(await page.locator('#story-content').textContent(),/八重事代主神/);
await page.keyboard.press('ArrowRight');assert.equal(await page.getByRole('tab',{name:'記錄的人'}).getAttribute('aria-selected'),'true');
await page.screenshot({path:output+'/suwa-expanded.png',fullPage:true});
await page.locator('#date-chart').screenshot({path:output+'/suwa-date-chart.png'});
await page.locator('#rolling-chart').screenshot({path:output+'/suwa-rolling-chart.png'});
await page.locator('#date-chart .year-date-mark[data-year="1960"]').click();
assert.equal(await page.locator('#year-title').textContent(),'1960');
assert.equal(await page.locator('#hero-art').getAttribute('src'),'assets/hero-unknown.png');
assert.equal(await page.locator('#show-legend').isHidden(),true);
assert.match(await page.locator('#notes-content .candidate-note').textContent(),/年度仍維持未知/);
await page.locator('#hero-art').evaluate(i=>i.decode());
await page.locator('.lake-section').screenshot({path:output+'/suwa-unknown.png'});
await page.locator('#date-chart .year-date-mark[data-year="2026"]').focus();await page.keyboard.press('Enter');
assert.equal(await page.locator('#year-title').textContent(),'2026');
assert.equal(await page.locator('#hero-art').getAttribute('src'),'assets/hero-not-observed.png');
await page.locator('#hero-art').evaluate(i=>i.decode());
await page.locator('.lake-section').screenshot({path:output+'/suwa-not-observed.png'});
await page.selectOption('#year-select','2018');await page.locator('#show-legend').click();
await page.locator('.legend-vignette').evaluate(i=>i.decode());
assert.match(await page.locator('#dialog-content').textContent(),/傳說演出/);
await page.locator('#event-dialog').screenshot({path:output+'/suwa-legend.png'});
await page.keyboard.press('Escape');
await page.selectOption('#year-select','2018');await page.selectOption('#month','2');await page.selectOption('#day','3');
await page.evaluate(()=>document.querySelectorAll('details').forEach(d=>d.open=false));await page.evaluate(()=>window.scrollTo(0,0));
await page.locator('#male').click();assert.equal(await page.locator('#companion-message').isVisible(),true);
// File:// offline smoke: no runtime HTTP/CDN request required.
const offline=await context.newPage();const outbound=[];offline.on('request',r=>{if(/^https?:/.test(r.url()))outbound.push(r.url());});
await offline.goto('file://'+root+'/dist/index.html');assert.equal(await offline.locator('#year-title').textContent(),'2018');assert.equal(outbound.length,0);await offline.close();
const mobile=await browser.newContext({viewport:{width:360,height:800},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto(base);
assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.equal(await mp.locator('#date-chart .year-date-mark').count(),150);
assert.equal(await mp.locator('#hero-art').evaluate(i=>getComputedStyle(i).animationName),'none');
await mp.screenshot({path:output+'/suwa-mobile.png',fullPage:true});
await mp.locator('#female').tap();assert.equal(await mp.locator('#companion-message').isVisible(),true);
await mp.selectOption('#nights','7');assert.equal(await mp.locator('.calendar-day.selected').count(),8);
await mp.locator('#archive-link').tap();await mp.locator('[data-year="2025"]').first().tap();assert.equal(await mp.locator('#year-title').textContent(),'2025');
await mp.locator('#date-chart').scrollIntoViewIfNeeded();
await mp.locator('#date-chart').screenshot({path:output+'/suwa-mobile-chart.png'});
await mp.locator('#date-chart .year-date-mark[data-year="1960"]').tap();
assert.equal(await mp.locator('#year-title').textContent(),'1960');
await mp.locator('#male').tap();assert.equal(await mp.locator('#companion-message').isVisible(),true);
assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.equal(errors.length,0,errors.join('\n'));assert.equal(failures.length,0,JSON.stringify(failures));
const report={status:'PASS',desktop:'1440×1100',mobile:'360×800 touch emulation',checks:['dates','leap day validation','stay drag and click','random known year','unknown winter','2026 ice distinction','event modal','150-year grid','statistics range','CSV 150 rows','story keyboard tabs','character tips','keyboard calendar focus','file offline no outbound requests','mobile no horizontal page overflow','mobile touch controls','two orange date-conflict corners','150 date and coverage markers','30-year filter','three hero states','candidate notes excluded from statistics','two vignette assets','chart keyboard navigation','reduced motion'],errors,failures};
fs.writeFileSync(output+'/browser-report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
await browser.close();
